theme: jekyll-theme-minimal
title: Katelyn Neff
description: (⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿
description: [About Me](https://k8neff.github.io/About)
descripton: [Work](https://k8neff.github.io/Work)
description: [Art](https://k8neff.github.io/Art)

