theme: jekyll-theme-minimal
title: Katelyn Neff
description: (⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿
description: *[About Me](https://k8neff.github.io/About)<br/>
descripton: *[Work](https://k8neff.github.io/Work)<br>
description: *[Art](https://k8neff.github.io/Art)<br/>

