theme: jekyll-theme-minimal
title: **Katelyn Neff**
description: Hi! I'm an Environmental Scientist studying at Hunter College in New York. 
*Interests include
  * Ecology
  * Wetland Restoration
  * GIS
  * Sustainability
